Omar manassra python 2 task
AHL-Logics-backend-tranining-2024/python-task-2 pull request #2
Opened 2024-08-19 14:41 UTC by Omarmanassrah

In update function in task_manager how i let the index if the list match the index i want to update

2024-08-20 17:28 UTC, Mohammed-samaheen requested changes

2024-08-20 17:28 UTC, Mohammed-samaheen commented on OmarManassra/__pycache__/task.cpython-312.pyc
We shouldn't include the Python cached files (Cython files). Please add the pycache folder to the .gitignore

2024-08-20 17:28 UTC, Mohammed-samaheen commented on OmarManassra/task_manager.py
> +        if isUrgant in ["yes","no"]:
"is_urgent (bool): any shape of yes and no is considered as a valid input"

2024-08-20 17:28 UTC, Mohammed-samaheen commented on OmarManassra/task_manager.py
> +tasks_list=[]
why did you use a list to store your value, why not use a dictionary with the key task if and value the task itself?

2024-08-21 08:58 UTC, Omarmanassrah commented
Done i will push the changes please see the changes and give a feedback
Thank you

2024-08-21 11:48 UTC, Mohammed-samaheen commented on OmarManassra/__pycache__/task.cpython-312.pyc
same issue

2024-08-21 11:50 UTC, Mohammed-samaheen commented on OmarManassra/Read.md
Let's just stick with README.md as the file name

2024-08-21 11:51 UTC, Mohammed-samaheen commented on OmarManassra/.gitignore
git will not see this file, you should add it to the main directory

2024-08-21 11:53 UTC, Mohammed-samaheen commented
resolve the conflict

2024-08-21 16:16 UTC, Mohammed-samaheen commented on OmarManassra/__pycache__/task.cpython-312.pyc
I added [.gitignore](https://github.com/AHL-Logics-backend-tranining-2024/python-task-2/blob/main/.gitignore) so please update your code, and remove the unwanted files.

2024-08-22 06:58 UTC, AMROAMRO404 commented on OmarManassra/task.py
> +    def __init__(self,priority,title,description,due_date,status="In progress"):
``
```suggestion
    def __init__(self,priority,title,description,due_date,status="InProgress"):
```

2024-08-22 06:59 UTC, AMROAMRO404 commented
can you please use prettier for formatting the code ?

2024-08-22 06:59 UTC, AMROAMRO404 commented
can you resolve the conflict in .gitignore ?

2024-08-22 07:01 UTC, AMROAMRO404 commented on OmarManassra/task_manager.py
> +            task.status = status
I see there are multiple lines duplicated, i think you can refactor it to mitigate this duplication.

2024-08-22 07:02 UTC, AMROAMRO404 commented on OmarManassra/task_manager.py
> +                 Delete_Task()
can you use lower_case for naming the methods ?

2024-08-22 07:03 UTC, AMROAMRO404 commented on OmarManassra/task_manager.py
> +        isUrgant=input("enter if urgant or not (True or False)")
please use snack case for naming the variables.

2024-08-22 07:05 UTC, AMROAMRO404 commented on OmarManassra/utils.py
> +        raise ValueError("the value Date is not right ")
we need to have a general validation not a specific date.

2024-08-22 07:07 UTC, AMROAMRO404 commented on OmarManassra/__pycache__/task.cpython-312.pyc
can you remove this file.

2024-08-22 07:07 UTC, AMROAMRO404 commented on OmarManassra/__pycache__/utils.cpython-312.pyc
can you remove this file.

2024-08-22 10:42 UTC, Omarmanassrah commented
@AMROAMRO404 
I made all the changes that is required if you can see it and give feedback if there is anything else
In .gitignore I accept both changes

2024-08-22 12:07 UTC, Mohammed-samaheen commented on .gitignore
No need to add this file

2024-08-23 12:43 UTC, Omarmanassrah commented on .gitignore
??!

2024-08-24 08:28 UTC, Momen-G-Ar commented on OmarManassra/task_manager.py
I think you have to install a spell checker, (recommended VSCode extension ID): `streetsidesoftware.code-spell-checker`

2024-08-24 08:35 UTC, Momen-G-Ar commented on OmarManassra/utils.py
> +    if status=="Complate" or status=="InProgress":
`Completed` not `Complate`, the user will confused when he writes Completed and got an Error

2024-08-24 08:36 UTC, Momen-G-Ar commented on OmarManassra/task_manager.py
> +            addtask=Task(title,description,due_date,status)
Please use snack case, `add_task`

2024-08-24 08:42 UTC, Momen-G-Ar commented on OmarManassra/task_manager.py
> +def update_task():
What happens if the `task_id `is not in the `tasks_dict`? 
I think that the task manager should tell the user that the `id` does not exist before entering all this information

2024-08-24 08:59 UTC, Momen-G-Ar reviewed
There is a conflict in `.gitignore` file, please resolve it

2024-08-24 09:17 UTC, Omarmanassrah commented
@Momen-G-Ar 
Momen I do not know the conflict is were can you give me more information in .gitignore which line is it the .gitignore in home directory

2024-08-24 09:27 UTC, Momen-G-Ar commented
> @Momen-G-Ar Momen I do not know the conflict is were can you give me more information in .gitignore which line is it the .gitignore in home directory

![image](https://github.com/user-attachments/assets/36dded21-83c7-4c48-9f33-2e66ece5626e)

2024-08-24 09:39 UTC, Omarmanassrah commented
@Momen-G-Ar can you see if I fix it

2024-08-29 05:01 UTC, Mohammed-samaheen approved these changes

2024-08-29 14:47 UTC, merged