Fatma qunnies python 2 task
AHL-Logics-backend-tranining-2024/python-task-2 pull request #3
Opened 2024-08-19 15:33 UTC by fatmaQunnies

The code implements a Task Manager Console Application in Python, utilizing object-oriented principles to manage tasks effectively. It includes features for adding, viewing, updating, and deleting tasks, with robust input validation and error handling to ensure stability and user-friendly interaction.

2024-08-19 17:25 UTC, Mohammed-samaheen commented on FatmaQunnies/Task.py
> +    def __init__(self, title, description, due_date, status = 'InProgress'):
I like the idea of using a default value for the status. However, I wanted to mention something I didn't bring up before: you can use [enums](https://docs.python.org/3/library/enum.html) in Python. This way, if we ever want to update the InProgress value to something like in-progress, we only need to update the enum. But anyway, great work!

2024-08-19 17:52 UTC, Mohammed-samaheen commented on README.md
Don't update this README file, instead create a new one in you folder

2024-08-19 18:06 UTC, Mohammed-samaheen requested changes

2024-08-19 18:06 UTC, Mohammed-samaheen commented on FatmaQunnies/Utils.py
> +    while True:
The validation function should focus only on the validation, so user input shouldn't be part of the validation process. Instead, we should store all the user input data as-is (without any validation) in a dictionary with key-value pairs. Then, you can either iterate over that dictionary to run the validation functions OR create a class—let's say UserTaskInputData and perform all the validations within that class.

2024-08-21 16:14 UTC, Mohammed-samaheen commented
I added [.gitignore](https://github.com/AHL-Logics-backend-tranining-2024/python-task-2/blob/main/.gitignore)

2024-08-22 06:49 UTC, AMROAMRO404 commented on FatmaQunnies/Task.py
> +# print(task3.display())
can you please delete these lines?

2024-08-22 06:49 UTC, AMROAMRO404 commented on FatmaQunnies/Task_manager.py
> +  print("Task added successfully.")
what if this code raise an error, how you would handle it ?

2024-08-22 06:49 UTC, AMROAMRO404 commented on FatmaQunnies/Task_manager.py
> +    print("Task not found.")
same thing here, what if this code raise an error?

2024-08-22 06:50 UTC, AMROAMRO404 commented on FatmaQunnies/Task_manager.py
> +# delete_task()
can you please delete these lines ?

2024-08-22 06:50 UTC, AMROAMRO404 commented on FatmaQunnies/Utils.py
> +        #     return status
here too

2024-08-22 06:50 UTC, AMROAMRO404 commented on FatmaQunnies/Utils.py
> +        #user_input = input(inputt).strip()
here too.

2024-08-22 06:50 UTC, AMROAMRO404 commented on FatmaQunnies/urgent_task.py
> +# print(urgent_task.display())
here

2024-08-22 06:51 UTC, AMROAMRO404 commented on FatmaQunnies/urgent_task.py
> +urgent_task = UrgentTask("Important Task", "Review ", "2024-08-05", "Medium")
here too.

2024-08-22 06:53 UTC, AMROAMRO404 commented on FatmaQunnies/Task_manager.py
> +        tasks.append(task)
can you please update the indentation here ?

2024-08-22 06:54 UTC, AMROAMRO404 commented on FatmaQunnies/Task_manager.py
> +    tasks.append(task)
`tasks.append(task)` called twice in this if-else block, maybe we can have only one ?

2024-08-22 06:56 UTC, AMROAMRO404 commented
maybe you can use prettier for formatting ?

2024-08-22 06:57 UTC, AMROAMRO404 commented
can you please resolve the confilct ?

2024-08-24 08:55 UTC, Mohammed-samaheen requested changes

2024-08-24 08:55 UTC, Mohammed-samaheen commented on FatmaQunnies/utils.py
> +        if re.match(r'^\d{4}-\d{2}-\d{2}$', date_str):
you can use `datetime` instead of regex.

2024-08-24 08:55 UTC, Mohammed-samaheen commented on FatmaQunnies/utils.py
> +        if status.upper() in Status.__members__:
Using the upper() method will convert all the letters to uppercase. `inProgress` != `INPROGRESS`

2024-08-24 08:55 UTC, Mohammed-samaheen commented on FatmaQunnies/utils.py
> +    while True:
Am I missing something? Why is there a while loop?

2024-08-24 08:55 UTC, Mohammed-samaheen commented on FatmaQunnies/utils.py
> +        priority = input("Enter the priority (high/medium/low) ").strip().lower()
As mentioned, the input handling should not be included in the validation function.

2024-08-24 08:55 UTC, Mohammed-samaheen commented on FatmaQunnies/task_manager.py
> +            if choice == '1':
you can use match statement.

2024-08-26 05:21 UTC, Mohammed-samaheen approved these changes
LGTM

2024-08-26 07:18 UTC, AMROAMRO404 approved these changes

2024-08-26 11:53 UTC, merged