Saja lahaleeh python 2 task
AHL-Logics-backend-tranining-2024/python-task-2 pull request #8
Opened 2024-08-22 01:58 UTC by sajalahalih

done all the task including the ponus except  the authentication

2024-08-22 07:12 UTC, AMROAMRO404 commented on saja/Task.py
> +    def validateDate(self, date):
please use snake case.

2024-08-22 07:14 UTC, AMROAMRO404 commented on saja/task_manager.py
> +    def add_task(self):
maybe we need to put this code under try/catch block ?
because the validation can raise an exceptions.

2024-08-22 07:14 UTC, AMROAMRO404 commented on saja/task_manager.py
> +    def update_task(self):
maybe we need to put this code under try/catch block ?
because the validation can raise an exceptions.

2024-08-22 07:16 UTC, AMROAMRO404 commented
can you please prettier for formatting ?

2024-08-24 09:32 UTC, Mohammed-samaheen approved these changes

2024-08-24 09:32 UTC, Mohammed-samaheen commented on saja/task_manager.py
> +        if choice == '1':
You can use a match statement; it's more readable.

2024-08-24 09:32 UTC, Mohammed-samaheen commented on saja/task_manager.py
> +            self.tasks = []
No need to update anything here. Consider using a dictionary instead of a list, with the task ID as a key.

2024-08-24 09:32 UTC, Mohammed-samaheen commented on saja/Task.py
> +        self.id = uuid.uuid4()  # Generate a unique identifier for the task.
Good choice, using the UUID is the best option especially when we have multiple replicas of the same app.

2024-08-24 09:32 UTC, Mohammed-samaheen commented on saja/task_manager.py
> +    def __new__(cls, *args, **kwargs):
Nice idea for using the singleton for the task manager.

2024-08-26 07:14 UTC, AMROAMRO404 commented on saja/task_manager.py
> +    def update_task(self):
@sajalahalih have you managed to update this ?

2024-08-26 07:16 UTC, AMROAMRO404 requested changes
My previous comments were not resolved, or replayed.

2024-08-26 21:07 UTC, sajalahalih commented
i resolved all the comments

2024-08-31 11:28 UTC, merged